//Try Catch

const numero1 = 20;
const numero3 = 30;

console.log(numero1);

try {
    console.log(numero2);
} catch (error) {
    console.log(error);
}

console.log(numero3); //Como la 2 no se definio la 3 no se ejecuta
